[project]
name = "llama-stack-chat-example-01"
version = "0.1.0"
description = "A simple 'three-tier' (ollama inference, stack, GUI) Llama Stack example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack>=0.2.15",
    "llama-stack-client>=0.2.15",
]
